name: Native Build
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Display release tag
        run: echo ${{ github.event.release.tag_name }}
      - name: Pull Docker Image
        run: docker pull gradle:jdk21-graal-jammy
      - name: Gradle Build
        run: |
          docker run --rm \
            -e GITHUB_REF=${{ github.ref }} \
            -e GITHUB_SHA=${{ github.sha }} \
            -e PLUGIN_ORGCONFIG=https://raw.githubusercontent.com/vaccovecrana/org-config/refs/heads/main/vacco-oss-java-21.json \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            gradle:jdk21-graal-jammy \
            gradle clean build nativeCompile
      - name: Upload binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: ot-app/build/native/nativeCompile/opt1x-*
          file_glob: true
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./ot-app
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/opt1x:${{ github.ref_name }}
          file: ./ot-app/Dockerfile